#!/bin/sh
# find and summarize the stats I'm supposed to put on run summary sheets
if [[ $1 -eq "" ]]; then
    echo "I need a Run Number!"
    exit 2
fi
RUNNUMBER=$1
SCALERFILE="OUTPUT/scalers_Run$RUNNUMBER.txt"
REPORTFILE="../REPORT_OUTPUT/COIN/PRODUCTION/replay_coin_production_${RUNNUMBER}_-1.report"
MONITORFILE="../MON_OUTPUT/REPORT/reportMonitor_shms_${RUNNUMBER}_50000.txt"
echo "========================================================================="
echo "RunSheet Stats for run $RUNNUMBER ...."
echo "----------Results from file <$SCALERFILE>...----------"
echo 
echo "Enter this for HMS prescale pretrig      vvvvvv"
#grep 'SHMS_pTRIG3 Pre-scaled Pre-triggers  :' OUTPUT/scalers_Run$RUNNUMBER.txt
grep 'SHMS_pTRIG3 Pre-scaled Pre-triggers  :' $SCALERFILE
echo
echo "Enter this for SHMS prescale pretrig     vvvvvv"
grep 'SHMS_pTRIG1 Pre-scaled Pre-triggers  :' $SCALERFILE
echo
echo "Enter this for COIN pretrig   vvvvvv"
grep 'SHMS_pTRIG5 Pre-triggers  :' $SCALERFILE
echo
echo "----------Results from file <$REPORTFILE>...----------"
echo "HMS Rate                                 vvvvvvv"
grep '^HMS_pTRIG3 Pre-triggers :' $REPORTFILE
echo
echo "SHMS Rate                                 vvvvvvv"
grep 'SHMS_pTRIG1 Pre-triggers :' $REPORTFILE
echo
echo "COIN Rate...                                      vvvvvv"
grep 'SHMS_pTRIG5 Pre-scaled Pre-triggers :' $REPORTFILE
echo
echo "Charge                      vvvvvvv"
grep 'SHMS BCM4B Beam Cut Charge:' $REPORTFILE
echo
echo "Number of raw-coin                   vvvvvvv"
grep 'Coin ROC2 pTRIG5 Accepted Triggers :' $REPORTFILE
echo
echo "----------Results from file <$MONITORFILE>...----------"
echo "Enter this for SHMS_h_tracking...    vvvvvv"
grep 'HADRON SING FID TRACK EFFIC     :' $MONITORFILE
echo
grep rate "../MON_OUTPUT/REPORT/reportMonitor_shms_${RUNNUMBER}_50000.txt"
echo "========================================================================="
